### PR TITLE
test: some fdo container test fixes

### PR DESCRIPTION
**Pull request by henrywang**
1. change fdouser file location to workaround issue https://bugzilla.redhat.com/show_bug.cgi?id=2026795#c24
2. fix ssh key permission issue
3. run podman in root mode for network inter-connection
4. workflow job status fix
5. disable selinux on FDO server host and edge vm to workaround bug https://bugzilla.redhat.com/show_bug.cgi?id=2026795
6. fix Makefile `make rpm` failure

### CODE REVIEW

**Comment by henrywang** [comment]
Hi @puiterwijk! I got the code scanning error for my `podman image scp $(whoami)@localhost::localhost/manufacturing-server root@localhost::` code. It reports `Accessing localhost could indicate debug code, or could hinder scaling` error.
This `localhost` part is to copy image from root-less to root on the same host. It's not debug and no scale needed.
May I skip this scanning error? Thanks.

**Comment by henrywang** [comment]
@7flying I disabled selinux on FDO server host and edge vm to workaround bug https://bugzilla.redhat.com/show_bug.cgi?id=2026795. Test passed. I think we can land this PR now. We can use `/test-container` to test FDO container for every PR.
I'll remove selinux disable workaround when bug got fixed.

**Review by 7flying — APPROVED** [review]
LGTM

**Pull request merged**
