### PR TITLE
chore: bump for 0.4.7 release

### PR DESCRIPTION
**Pull request by nullr0ute**
Prepare for the 0.4.6 release.
Add Cargo.lock file as we're producing executables.

Signed-off-by: Peter Robinson <pbrobinson@gmail.com>

### CODE REVIEW

**Comment by 7flying** [comment]
@nullr0ute it should say 0.4.7 on the commit message description too, but other than that :+1:

**Comment by nullr0ute** [comment]
> @nullr0ute it should say 0.4.7 on the commit message description too, but other than that +1

:laughing: fixed

**Review by 7flying — DISMISSED** [review]
LGTM!

**Review by 7flying — APPROVED** [review]
LGTM

**Comment by 7flying** [comment]
@runcom we need another reviewer to merge these changes

**Review by paulwhalen — APPROVED** [review]
LGTM

**Pull request merged**
