### PR TITLE
Add dependabot configuration

### PR DESCRIPTION
**Pull request by puiterwijk**

### CODE REVIEW

**Comment by nullr0ute** [comment]
What does dependabot do? A little bit of detail in the commit would be useful, overall seems OK

**Comment by puiterwijk** [comment]
[Dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates) automatically determines outdated dependencies, and submits PRs to update them.

**Comment by puiterwijk** [comment]
@nullr0ute added more info to the actual commit message.

**Review by nullr0ute — APPROVED** [review]
With the updated commit it LGTM

**Pull request merged**
