### PR TITLE
fix: format in TESTING.md

### PR DESCRIPTION
**Pull request by nak3**
This patch fixes the format of [TESTING.md](https://github.com/fedora-iot/fido-device-onboard-rs/blob/main/TESTING.md).

### CODE REVIEW

**Review by nullr0ute — DISMISSED** [review]
LGTM

**Comment by 7flying** [comment]
@nak3 we'll also need you to change your commit format here to something like: `fix: format in TESTING.md`

**Comment by nak3** [comment]
Sure, updated here as well. Thank you.

**Review by 7flying — APPROVED** [review]
Thank you!

**Pull request merged**
