### PR TITLE
chore: add client-linuxapp container

### LINKED ISSUE #499: Make a `client-linuxapp` container
We do not ship a container for the device client (`client-linuxapp`), but there is no reason why we couldn't ship it.

This would make it easier for non-Fedora users (see https://github.com/fedora-iot/fido-device-onboard-rs/issues/498) to take their first steps with FDO.

#### Acceptance criteria
- a `fdo-init` container is available on our [Quay repo](https://quay.io/organization/fido-fdo)

#### Testing
- ci is updated to include the build of this new container
- the onboarding flow is tested with containers

### PR DESCRIPTION
**Pull request by rdotjain**
This PR adds a fdo-client-linuxapp container.
- Updated CI/CD to include build of the container and push it to quay.io
- Updated README with commands to run the container
- FIxes #499

### CODE REVIEW

**Comment by runcom** [comment]
uhm, why is copr failing now :thinking:

**Comment by runcom** [comment]
cc @7flying

**Comment by rdotjain** [comment]
> uhm, why is copr failing now 🤔

i think this issue is reported in #506

**Comment by 7flying** [comment]
I'm not seeing the container show up in quay yet, shouldn't it be showing?

Now that we have the client, could we add a small test checking an e2e scenario?

**Comment by 7flying** [comment]
> uhm, why is copr failing now 

The specfile had some changes that @nullr0ute  needs to propagate over this repo in order to fix it, but it has already been tracked, `make rpm` is also broken due to these changes (but we have a workaround)

**Comment by rdotjain** [comment]
> I'm not seeing the container show up in quay yet, shouldn't it be showing?

it should be triggered after merge to main, i think?
 
> Now that we have the client, could we add a small test checking an e2e scenario?

do we want the tests to be part of same PR, or create another one?

**Comment by 7flying** [comment]
> > I'm not seeing the container show up in quay yet, shouldn't it be showing?
> 
> it should be triggered after merge to main, i think?
> 
> > Now that we have the client, could we add a small test checking an e2e scenario?
> 
> do we want the tests to be part of same PR, or create another one?

forget about that last part

**Comment by 7flying** [comment]
@paulwhalen can you please take a look?

**Review by paulwhalen — CHANGES_REQUESTED** [review]
Small change to the expected file name, otherwise LTGM.

**Review by paulwhalen — APPROVED** [review]
Thanks!

**Pull request merged**
