### PR TITLE
chore: Update libcryptsetup-rs to 0.7

### PR DESCRIPTION
**Pull request by nullr0ute**
Update to the latest libcryptsetup-rs upstream release. Also update the Cargo.lock as part of this.

### CODE REVIEW

**Comment by nullr0ute** [comment]
@7flying can you double check none of the API has changed with this bump in case we need to do more than just bump the rev.

**Comment by 7flying** [comment]
> @7flying can you double check none of the API has changed with this bump in case we need to do more than just bump the rev.

@nullr0ute All good, we do not need to change anything on our end.
The commitlint is failing due to an uppercase letter in your commit, other that that we can merge this.

**Comment by nullr0ute** [comment]
> > @7flying can you double check none of the API has changed with this bump in case we need to do more than just bump the rev.
> 
> @nullr0ute All good, we do not need to change anything on our end. The commitlint is failing due to an uppercase letter in your commit, other that that we can merge this.

Should be fixed

**Review by 7flying — APPROVED** [review]
LGTM

**Pull request merged**
