### PR TITLE
docs: add a general HOWTO.md file

### LINKED ISSUE #300: Add non-aio how-to-run documentation
Some testing/developing use cases may require to run just a single server of the FIDO onboarding infrastructure (like testing FDO servers in separate containers). 

We should:
- add documentation on how to run/configure each service
- add documentation on how to generate OVs with the owner tool, extend those with the required certificates and so on

so that there is little need to read the source code.

### PR DESCRIPTION
**Pull request by 7flying**
This contains general recipes on how to do things and documentation on the different command-line tools and config files that are in use.

Closes #300.

### CODE REVIEW

**Comment by nullr0ute** [comment]
Overall this looks great. I'd be happy to merge this as is and then we can follow up with more PRs to improve on top.

**Comment by 7flying** [comment]
@nullr0ute, great! Marking it as ready.

**Review by nullr0ute — APPROVED** [review]
LGTM

**Comment by nullr0ute** [comment]
The CI failure is unrelated and has been filed as #315

**Pull request merged**
